### ISSUE TITLE
npm not found in spawn()

### ISSUE THREAD

**Issue by filfat** [vdemedes/gifi#13]
**Windows 10,**

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn npm ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by casmith** [comment]
What version of Node/NPM?

**Comment by naueramant** [comment]
Same here on Node 5.7.0 and NPM 3.7.3

**Comment by vdemedes** [comment]
@filfat @naueramant I released a new version on npm (`1.2.0`), that is supposed to fix this issue. Would you mind updating and checking if the issue still there? Thanks!

**Comment by naueramant** [comment]
It now works! :+1:

**Comment by vdemedes** [comment]
Awesome, thanks @dsblv!
